# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Release Candidate

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    name: Build Release Candidate for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          cache: 'sbt'
      - name: Run native image
        run: |
          sbt graalvm-native-image:packageBin
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: bazel-bsp-${{ matrix.os }}
          path: target/graalvm-native-image/bazel-bsp
